Traceback (most recent call last):
  File "/home/eligran12/anaconda3/envs/Ingenieria/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/eligran12/anaconda3/envs/Ingenieria/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eligran12/anaconda3/envs/Ingenieria/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eligran12/anaconda3/envs/Ingenieria/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/eligran12/anaconda3/envs/Ingenieria/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/eligran12/anaconda3/envs/Ingenieria/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/eligran12/anaconda3/envs/Ingenieria/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig = plt.figure(figsize=(9,6))
externForceNumerical([1.2], 0.2, 1, 0., 0.5, 4.)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[4], line 2[0m
[1;32m      1[0m fig [38;5;241m=[39m plt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m9[39m,[38;5;241m6[39m))
[0;32m----> 2[0m [43mexternForceNumerical[49m[43m([49m[43m[[49m[38;5;241;43m1.2[39;49m[43m][49m[43m,[49m[43m [49m[38;5;241;43m0.2[39;49m[43m,[49m[43m [49m[38;5;241;43m1[39;49m[43m,[49m[43m [49m[38;5;241;43m0.[39;49m[43m,[49m[43m [49m[38;5;241;43m0.5[39;49m[43m,[49m[43m [49m[38;5;241;43m4.[39;49m[43m)[49m

Cell [0;32mIn[3], line 7[0m, in [0;36mexternForceNumerical[0;34m(fd_values, theta, m, w, gamma, l)[0m
[1;32m      5[0m theta [38;5;241m=[39m [theta]
[1;32m      6[0m [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;28mlen[39m(time)[38;5;241m-[39m[38;5;241m1[39m):
[0;32m----> 7[0m   w[38;5;241m.[39mappend(w[i] [38;5;241m-[39m ( [43mg[49m[38;5;241m/[39ml [38;5;241m*[39m np[38;5;241m.[39msin(theta[i]) [38;5;241m+[39m gamma [38;5;241m*[39m w[i] [38;5;241m-[39m (FD[38;5;241m/[39mm) [38;5;241m*[39m np[38;5;241m.[39mcos([38;5;241m2[39m[38;5;241m/[39m[38;5;241m3[39m [38;5;241m*[39m time[i]) )[38;5;241m*[39mtime[[38;5;241m1[39m])
[1;32m      8[0m   theta[38;5;241m.[39mappend(theta[i] [38;5;241m+[39m w[i[38;5;241m+[39m[38;5;241m1[39m][38;5;241m*[39mtime[[38;5;241m1[39m])
[1;32m      9[0m plt[38;5;241m.[39mplot(time, theta, label [38;5;241m=[39m [38;5;124mf[39m[38;5;124m"[39m[38;5;124mFD = [39m[38;5;132;01m{[39;00mFD[38;5;132;01m}[39;00m[38;5;124m"[39m)

[0;31mNameError[0m: name 'g' is not defined

